/* Main.c file generated by New Project wizard
 *
 * Created:   Sat May 11 2024
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>




#define MAX_VOLTAGE 5.0 // Maximum voltage range of the sensor (in volts)

void initialize_ADC() {
    // Configure ADCON1 register for analog input channels
    ADCON1bits.PCFG = 0b0000; // Set AN0-AN7 as analog inputs
    // Configure ADCON0 register
    ADCON0bits.ADCS = 0b01; // Fosc/8 as ADC conversion clock
    ADCON0bits.ADON = 1; // Enable ADC module
}

unsigned int read_ADC(unsigned char channel) {
    ADCON0bits.CHS = channel; // Select the specified channel
    __delay_us(10); // Wait for acquisition time (if needed)
    ADCON0bits.GO = 1; // Start ADC conversion
    while (ADCON0bits.GO); // Wait for conversion to complete
    return (ADRESH << 8) | ADRESL; // Return the 10-bit ADC result
}

void main() {
    // Initialize ADC module
    initialize_ADC(); 

    // Set RB0 and RB1 as outputs for LEDs
    TRISBbits.TRISB0 = 0; // Set RB0 as output
    TRISBbits.TRISB1 = 0; // Set RB1 as output
    
    // Control LEDs based on sensor values in the main loop
    while(1) {
        // Read analog values of three sensors connected to AN0, AN1, and AN2
        int soil_moisture_1 = read_ADC(0); // Read sensor connected to AN0
        int soil_moisture_2 = read_ADC(1); // Read sensor connected to AN1
        int water_level = read_ADC(2); // Read sensor connected to AN2

        // Determine the values of B1V and B2V based on sensor readings
        int B1V, B2V;
        if (soil_moisture_1 > (40 * 1024 / MAX_VOLTAGE) &&
            soil_moisture_2 > (40 * 1024 / MAX_VOLTAGE) &&
            water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B2V = 1;
            B1V = 1;
        }
	 else if (soil_moisture_1 < (40 * 1024 / MAX_VOLTAGE) &&
            soil_moisture_2 < (40 * 1024 / MAX_VOLTAGE) ) {
            B2V = 0;
            B1V = 0;
        }	
	else if (soil_moisture_1 <= (40 * 1024 / MAX_VOLTAGE) &&
                   water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B1V = 1;
            B2V = 0;
        } else if (soil_moisture_2 <= (40 * 1024 / MAX_VOLTAGE) &&
                   water_level > (20 * 1024 / MAX_VOLTAGE)) {
            B1V = 0;
            B2V = 1;
        }
	else{
	   B2V = 0;
           B1V = 0;
	   }
        // Control LEDs based on B1V and B2V
        PORTBbits.RB0 = B1V; // Turn on RB0 if B1V is 1
        PORTBbits.RB1 = B2V; // Turn on RB1 if B2V is 1

        // Add delay to slow down sensor readings
        __delay_ms(1000);
    }
}
